version: '3'

services:
  commander:
    build:
      context: .
      dockerfile: ./Commander/Dockerfile
    container_name: com_container
    volumes:
      - ./log_volume:/app/input

  general1:
    build:
      context: .
      dockerfile: ./General1/Dockerfile
    container_name: g1_container
    volumes:
      - ./log_volume:/app/input

  general2:
    build:
      context: .
      dockerfile: ./General2/Dockerfile
    container_name: g2_container
    volumes:
      - ./log_volume:/app/input
  
  general3:
    build:
      context: .
      dockerfile: ./ByzantineNode/Dockerfile
    container_name: g3_container
    volumes:
      - ./log_volume:/app/input

  general4:
    build:
      context: .
      dockerfile: ./General4/Dockerfile
    container_name: g4_container
    volumes:
      - ./log_volume:/app/input
